name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install application dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Check types
        run: pnpm types:check

      - name: Run integration tests
        run: pnpm test
